### ISSUE TITLE
[SEVERE] Migrate to Google Sign-In

### ISSUE THREAD

**Issue by martymcguire** [martymcguire/epluribus#22]
[Google+ APIs are going away](http://www.google.com/appserve/mkt/p/AEM7UVSEXeQ27XHkQyqzJwH1Kw7moE2PN7LoqXmgXEwmRsOhp7V5bHRcRmMnDl6fm9qR-loHtw_oALwe2oTnMHxG_aL9YQlkFNBPZYqQdBM).

Migrate our sign-in stuff to use [Google Sign-In](https://developers.google.com/identity/).

**Comment by tblatt** [comment]
OMG

**Comment by martymcguire** [comment]
it's not going away until March so we have plenty of time. :}

**Comment by martymcguire** [comment]
I did a pass over our "sign in with google" functionality and updated the button to their latest branding.

basically: we weren't actually using the G+ API in any way. So, I disabled the G+ API in our Google Developer Console.

I can still login and out just fine, so, 🤷🏻‍♂️
